### ISSUE TITLE
Partition names...

### ISSUE THREAD

**Issue by jakezp** [jpbarraca/pai#20] opened 2018-11-30 22:25 UTC
Panel MG5050 version 5.33 build 2

Why did the partition names update from Area_1 / Area_2 to Output_07_______Output_08, Output_08_______Output_09

Log output:
>2018-11-30 22:18:19,178 - INFO     - PAI.paradox.hardware.panel - Partition: Output_07_______Output_08, Output_08_______Output_09

Is this change permanent? Or is it something I need to configure on my panel / alarm?

**Comment by jakezp** [comment] 2018-11-30 22:30
Digging a bit further, everything looks different:

`2018-11-30 22:18:18,416 - INFO     - PAI.paradox.hardware.panel - Zone: FRONT_DOOR______KITCHEN_PASSAGE, KITCHEN_PASSAGE_ARM_DISARM_TWO, ARM_DISARM_TWO__ARM_DISARM, ARM_DISARM______PANIC, PANIC___________BACK_DOOR_WINDOW, BACK_DOOR_WINDOWBATHROOMS_WINDOW, BATHROOMS_WINDOWBEDROOMS_WINDOWS, BEDROOMS_WINDOWSDINING&LNGE_PIR, DINING&LNGE_PIR_MARKUS_ROOM_PIR, MARKUS_ROOM_PIR_PLAY_&_SPARE_PIR, PLAY_&_SPARE_PIRMAINBED_PIR, MAINBED_PIR_____STUDY_WINDOW, STUDY_WINDOW____STUDY_PIR, STUDY_PIR_______ENTRANCE_BEAM, ENTRANCE_BEAM___BRAAI_BEAM, BRAAI_BEAM______DOUBLE_GARAGE_PI, DOUBLE_GARAGE_PIBACK_ALLEY, BACK_ALLEY______KITCHEN_BEAM, KITCHEN_BEAM____SIDE_BEAM, SIDE_BEAM_______MAINBED_BEAM, MAINBED_BEAM____LEFT_GARAGE_PIR, LEFT_GARAGE_PIR_Zone_23, Zone_23_________Zone_24, Zone_24_________Zone_25, Zone_25_________Zone_26, Zone_26_________Zone_27, Zone_27_________Zone_28, Zone_28_________Zone_29, Zone_29_________Zone_30, Zone_30_________Zone_31, Zone_31_________Zone_32, Zone_32_________Panic_Radio
2018-11-30 22:18:18,993 - INFO     - PAI.paradox.hardware.panel - Output: Panic_Radio_____Burglary_Radio, Burglary_Radio__Status_LED, Status_LED______Open/Close_Radio, Open/Close_RadioOutput_05, Output_05_______Output_06, Output_06_______Output_07
2018-11-30 22:18:19,178 - INFO     - PAI.paradox.hardware.panel - Partition: Output_07_______Output_08, Output_08_______Output_09
2018-11-30 22:18:22,134 - INFO     - PAI.paradox.hardware.panel - User: Output_09_______Output_10, Output_10_______Output_11, Output_11_______Output_12, Output_12_______Output_13, Output_13_______Output_14, Output_14_______Output_15, Output_15_______Output_16, Output_16____________Area_1, Area_1__________Area_2, Area_2_____System_Master, System_Master___Master_1, Master_1________Master_2, Master_2________User_04, User_04_________User_05, User_05_________User_06, User_06_________User_07, User_07_________User_08, User_08_________User_09, User_09_________User_10, User_10_________User_11, User_11_________User_12, User_12_________User_13, User_13_________User_14, User_14_________User_15, User_15_________User_16, User_16_________User_17, User_17_________User_18, User_18_________User_19, User_19_________User_20, User_20_________User_21, User_21_________User_22, User_22_________User_23
2018-11-30 22:18:23,534 - INFO     - PAI.paradox.hardware.panel - Bus: User_23_________User_24, User_24_________User_25, User_25_________User_26, User_26_________User_27, User_27_________User_28, User_28_________User_29, User_29_________User_30, User_30_________User_31, User_31_________User_32, User_32_________Bus_Module_01, Bus_Module_01___Bus_Module_02, Bus_Module_02___Bus_Module_03, Bus_Module_03___Bus_Module_04, Bus_Module_04___Bus_Module_05, Bus_Module_05___Bus_Module_06
2018-11-30 22:18:23,716 - INFO     - PAI.paradox.hardware.panel - Repeater: Bus_Module_06___Bus_Module_07, Bus_Module_07___Bus_Module_08
2018-11-30 22:18:24,447 - INFO     - PAI.paradox.hardware.panel - Keypad: Bus_Module_08___Bus_Module_09, Bus_Module_09___Bus_Module_10, Bus_Module_10___Bus_Module_11, Bus_Module_11___Bus_Module_12, Bus_Module_12___Bus_Module_13, Bus_Module_13___Bus_Module_14, Bus_Module_14___Bus_Module_15, Bus_Module_15___Repeater_1
2018-11-30 22:18:24,540 - INFO     - PAI.paradox.hardware.panel - Site: Repeater_1______Repeater_2
2018-11-30 22:18:24,936 - INFO     - PAI.paradox.hardware.panel - Siren: Repeater_2______Wireless_Keyp_1, Wireless_Keyp_1_Wireless_Keyp_2, Wireless_Keyp_2_Wireless_Keyp_3, Wireless_Keyp_3_Wireless_Keyp_4`

All names were updated to name___name and the names do not match the devices:

Repeater: Bus_Module_06___Bus_Module_07, Bus_Module_07___Bus_Module_08

Repeater names are Bus_Module_06___Bus_Module_07 and Bus_Module_07___Bus_Module_08, as an example.

The only thing I did was recreate my docker container so the latest changes are pulled down. I did not change anything on my alarm.

**Comment by jpbarraca** [comment] 2018-11-30 22:45
It has to do with the merge of the EVO branch. 
Can you send a full debug with packet traces (email) ? The issue is not happening on a MG5050 v6.128.

**Comment by jpbarraca** [comment] 2018-11-30 23:17
Should be fixed

**Comment by jakezp** [comment] 2018-12-01 05:09
Seems to be fixed now. Thank you !

`2018-12-01 05:07:16,925 - INFO     - PAI.paradox.hardware.panel - Partition: Area_1, Area_2`

**Comment by yozik04** [comment] 2018-12-01 21:53
No problems with EVO and @jakezp confirmed that it is fixed. Closing.

**Closed by yozik04** 2018-12-01 21:53 UTC
Labels: bug, testing required
